### ISSUE TITLE
Can't make Kernkraft  work on Glyphs

### ISSUE THREAD

**Issue by ElenaPeraltaDimas** [carrois/Kernkraft#11]
Hello there,
So this is a silly situation but I am trying to make kernkraft work on glyphs [ Version 2.4.1 (983) ]. I used it last week but now it doesn't work anymore. 
After seeing it doesn't work I erased it from the script folder, I tried to reinstall vanilla from preferences>install modules but no pop up window showed up after writing the password ( So I assume it's fine). Then I both clicked on the kernkraft plug in file and I pasted it in the script folder. 
When I go to the plug in manager it says it's installed (I also tried to uninstall and re-install it from there).It's shown in the script appendix but when you click on it nothing happens, no pop up window with the tool. I've restarted the computer and rebooted glyphs several times.
I know the plug in is installed because when I click on the plug in file again I get:

Are you sure you want to install the plugin:
Kernkraft.glyphsPlugin?

The plugin will be placed in /Users/usuari/Library/Application Support/Glyphs/Plugins.

The plugin:
Kernkraft.glyphsPlugin
is already installed.

Do you want to override it?

And I have replaced it. Any idea on how to make it work?
In this situation I'm wondering if the problem is vanilla, glyphs or the plug-in. 
Thank you for your help!

**Comment by Mark2Mark** [comment]
Hi!

Thanks for reaching out.

First of all, are you just mixing up "scripts" folder with "plugins" folder here in the text, or actually in the environment? The plugin needs to be in the "plugins" folder anyway.

Next thing to find out: do you have it installed via the Plugin Manager **and** maually? Please remove all Kernkraft plugins you might have installed manually. Look into the "plugins" folder, find it, delete it. Then, check your "repositories" folder. It is right next to the "plugins" and "scripts" folder. In there, remove all Kernkraft stuff you find, too. Empty trash.

Now, please only install once via the Plugin Manager, restart GlyphsApp and see what happens.

If you find Kernkraft in the menu, launch it. If it doesn’t show up, please open the macro panel and tell me what’s written there.

**Comment by ElenaPeraltaDimas** [comment]
I did it all and now it works... I think it was both installed manually and via plug in manager.
Thank you for your help!

**Comment by Mark2Mark** [comment]
You’re welcome! Thanks for letting me know. Enjoy.
