### ISSUE TITLE
feature: remember last setting

### ISSUE THREAD

**Issue by neuedeutsche** [carrois/Kernkraft#12]
Would be neat if kernschmelze remembers what layers are the the source and which to apply to.
i have started using the plugin and run it relatively often so setting it to the same settings seems cumbersome after a while

**Comment by Mark2Mark** [comment]
You mean the Masters? That’s on my list already. Hope I’ll have the time soon to implement.

Thanks for reporting.

**Comment by neuedeutsche** [comment]
perfect, essentially just to be able to run last settings again is what i want if i wasnt clear

**Comment by Mark2Mark** [comment]
Thanks. Yes, I’ll implement saving the settings. Good point!

**Comment by neuedeutsche** [comment]
hey mark, i am curious…
has this been implemented?

**Comment by Mark2Mark** [comment]
Hey hey, I didn’t touch the code for a long time, so I can’t recall from the top of my head right now. I think I implemented a lot of that saving looong ago. Did you try? Is it still not working? If so, are you sure that you have the latest version?

**Comment by neuedeutsche** [comment]
i just checked if i have the last available and no its not remembering last settings.

**Comment by Mark2Mark** [comment]
Is there anything written in the Macro Panel?

My version (which is from this very repository) is storing the settings since ages. There must be something failing on your machine.
