### ISSUE TITLE
»… Slowing Down …« message

### ISSUE THREAD

**Issue by Mark2Mark** [carrois/Kernkraft#14]
@schriftgestalt 

Some users keep reporting that Kernkraft causes the GlyphsApp message that Kernkraft is slowing down Glyphs. I removed all wildcard imports from Appkit a while ago. Is there another reason that causes it?

Also, I put this question a month ago somewhere, but I cannot find it neither here nor in the Glyphs forum anymore.

**Comment by schriftgestalt** [comment]
Then it is most likely an old version of vanilla that still has the imports.

**Comment by Mark2Mark** [comment]
I’ll forward that info. Thanks!

**Comment by laerm0** [comment]
I just (finally) updated vanilla and got the "slowing down" message, so maybe that's not it.

**Comment by Mark2Mark** [comment]
@laerm0 can you please follow these steps (if you didn’t already)
https://forum.glyphsapp.com/t/manually-installing-vanilla-module/8807

I don’t get this message with this Kernkraft, so there must be something hanging in the pipes. :/
