### ISSUE TITLE
Glyphs Skipped

### ISSUE THREAD

**Issue by JamieClarkeType** [carrois/Kernkraft#17]
Hi Mark, Kernkraft doesn't seem to be including some glyphs even when all skip buttons are unchecked.
Missing from my char set: ◊ ¶ § ® ° | ¦ † ‡ № ℮ /degree.osf /bar.ss04
It is picking up: @ & ™
I'm using the latest version of Glyphs Version 2.6 (1192)

**Comment by Mark2Mark** [comment]
Hi @JamieClarkeType 

Thanks for reporting. I could finally fix it. I have no idea why I had to add these [exceptions manually here](https://github.com/bBoxType/Kernkraft/blob/master/Kernkraft.glyphsPlugin/Contents/Resources/Customizables.py) back when I wrote Kernkraft, but I added the glyphs you reported as missing. /ampersand, /at and /trademark where already there, so I assume that was the spot to go to.

Can you please check if it works? The .xxx suffix should not matter.

**Comment by JamieClarkeType** [comment]
Thanks Mark. Will check when back in the country.

Jamie
