### ISSUE TITLE
Plugin crash on startup in v2.6.5 (1342)

### ISSUE THREAD

**Issue by kalapi** [carrois/Kernkraft#22]
Getting this traceback on GlyphsApp startup. 

I'm on:
- macOS Catalina v 10.15.5 (19F101)
- GlyphsApp v 2.6.5 (1342)
- reinstalled Vanilla 

![kernkraft_plugin_crash](https://user-images.githubusercontent.com/15804460/94443118-53581080-0194-11eb-805c-41cb225f98c2.png)

**Comment by kalapi** [comment]
Tried updating to 2.6.6 (1346), no cigar!

**Comment by schriftgestalt** [comment]
Can you reinstall your vanilla library.

**Comment by kalapi** [comment]
Nope, doesn't work. I already reinstalled Vanilla several times because I had faced similar issues with 'RedArrows'.

**Comment by kalapi** [comment]
FWIW I tried importing the missing class in the terminal and I get the same error.

![Screenshot 2020-10-01 at 8 02 14 AM](https://user-images.githubusercontent.com/15804460/94759085-84039a00-038e-11eb-9e72-e44974d5e86f.png)

**Comment by schriftgestalt** [comment]
You need to install it from within Glyphs (in the latest cutting edge version). It should install a slightly older version as the latest code is not compatible with python2 any more.

**Comment by kalapi** [comment]
That fixed it, thanks!
