### ISSUE TITLE
Kernkraft shows errors on macro panel G3

### ISSUE THREAD

**Issue by ibo-o** [carrois/Kernkraft#27]
When I run the plugin properly, there are tons of error messages on the macro panel. But I don't know if the plugin works as expected or not because the plugin creates lots of strings but sometimes some glyphs aren't included. For instance numbers. 

```
Traceback (most recent call last):
  File "KernKraftModule.py", line 527, in hasKerning
    if len(anyKerning) == 1 and anyKerning[0].__long__() == 9223372036854775808:
AttributeError: 'NoneType' object has no attribute '__long__'
```

```
Traceback (most recent call last):
  File "KernKraftModule.py", line 511, in hasKerning
    if len(anyKerning) == 1 and anyKerning[0].__long__() == 9223372036854775808:
AttributeError: 'NoneType' object has no attribute '__long__'
```

**Comment by Mark2Mark** [comment]
Hi @obiobik 

Does this still happen? 
If so, wchih Glyphs Build do you have, and which Kernkraft version?

**Comment by ibo-o** [comment]
It was 3108. No more error messages in newer versions of Glyphs 3

**Comment by Mark2Mark** [comment]
Thank you!
