### ISSUE TITLE
Doesn't fit on 1280x800

### ISSUE THREAD

**Issue by dyyybek** [carrois/Kernkraft#4]
The window won't fit on a small res screen such as MacBook Pro 13" (non retina).

**Comment by Mark2Mark** [comment]
Thanks for reporting!
Never checked that before. I’ll try to find a solution.

**Comment by carrois** [comment]
Fixed it. Please try and let me know if it already helps.
Also, it is now possible to add the suite as a plugin (instead of a script).

**Comment by Mark2Mark** [comment]
@dyyybek Could you please confirm if it works for you now? If all is okay, I can close the issue. Thanks :)

**Comment by dyyybek** [comment]
I completely forgot! It is all fine now! The plugin window fits 1280x800 nicely. Thank you!

**Comment by Mark2Mark** [comment]
Thank you for reporting and checking back. Enjoy the plugin!

**Comment by Mark2Mark** [comment]
Quote from Georg from [this forum thread](https://forum.glyphsapp.com/t/kernkraft-cropped-window/9498/8):


> I see the problem. I tried it myself and it barely fits on the screen of my 15" MacBook. So the dialog is to big. I think you get it below 780 pt height it would be good.
> 
> You could use two columns for the “Ski Categories” box. And deduce the space between rows. And maybe remove some of the horizontal lines?
> 
> And how often do you change the settings? maybe put most info in an popup? Then you even could keep the window open after opening a tab.
>

**Comment by schriftgestalt** [comment]
I played a bit with the layout:
<img width="362" alt="screen shot 2018-08-03 at 09 28 42" src="https://user-images.githubusercontent.com/174660/43654329-bd841230-96ff-11e8-800f-2d189cb86048.png">

**Comment by Mark2Mark** [comment]
👍

**Comment by schriftgestalt** [comment]
Now you need to update the screenshot in the readme ;) You can use my screenshot from above if you like.

**Comment by Mark2Mark** [comment]
Thank you, done! :)
